language: python
python:
  - 3.4
  - 3.5
  - 3.6
install:
  - "pip install scipy" # install scipy first to satisfy later dependencies
  - "pip install -r requirements.txt"
script:
  - "flake8 ."
notifications:
  email:
    - ccn1u16@soton.ac.uk
