language: python
python:
  - 3.4
  - 3.5
  - 3.6
before_install:
  - "sudo apt-get install -y python-numpy python-scipy"
install:
  - "pip install -r requirements.txt"
script:
  - "flake8 ."
notifications:
  email:
    - ccn1u16@soton.ac.uk
